#!/usr/bin/php -c /etc/php.ini

<?php

 array_shift($argv);
 $f_notify_type =array_shift($argv);
 $f_host_name =array_shift($argv);
 $f_host_alias =array_shift($argv);
 $f_host_state =array_shift($argv);
 $f_host_address =array_shift($argv);
 $f_host_output =array_shift($argv);
 $f_long_date =array_shift($argv);
 $f_serv_desc  =array_shift($argv);
 $f_serv_state  =array_shift($argv);
 $f_to  =array_shift($argv);
 $f_totalup  =array_shift($argv);
 $f_totaldown=array_shift($argv);

 if($f_host_state=="RECOVERY") {$f_color="#f48400";}
 if($f_host_state=="DOWN") {$f_color="#f40000";}
 if($f_host_state=="UP") {$f_color="#00b71a";}

 $subject = "$f_notify_type Host:$f_host_name";
 $url = "nagios.yourdomain.com";

 $from  ="nagios@yourdomain.com";
 $body = "<html><body><table border=0 width='98%' cellpadding=0 cellspacing=0><tr><td valign='top'>\r\n";
 $body .= "<table border=0 cellpadding=0 cellspacing=0 width='98%'>";
 $body .= "<tr bgcolor=$f_color><td width='140'><b><font color=#ffffff>Host: </font></b></td><td><font color=#ffffff><b> $f_notify_type [$f_host_state]</b></font></td></tr> \r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Hostname: </b></td><td><b><a href='https://$url/#cgi-bin/extinfo.cgi?type=1&host=$f_host_name'>$f_host_alias</a></b></td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Address: </b></td><td><b>$f_host_address</b></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Date/Time: </b></td><td>$f_long_date</td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Info: </b></td><td><font color=$f_color>$f_host_output</font></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Total Hosts Up: </b></td><td>$f_totalup</td></tr>\r\n";
 $body .= "<tr bgcolor=#fefefe><td><b>Total Hosts Down: </b></td><td>$f_totaldown</td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td><b>Actions: </b></td><td><a href='https://$url/cgi-bin/cmd.cgi?cmd_typ=96&host=$f_host_name&service=$f_serv_desc'><b>Re-schedule next check</b></a></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td></td><td><a href='https://$url/cgi-bin/cmd.cgi?cmd_typ=55&host=$f_host_name&service=$f_serv_desc'><b>Schedule downtime for host</b></a></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td></td><td><a href='https://$url/cgi-bin/cmd.cgi?cmd_typ=86&host=$f_host_name&service=$f_serv_desc'><b>Schedule downtime for all services on host</b></a></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td></td><td><a href='https://$url/cgi-bin/cmd.cgi?cmd_typ=25&host=$f_host_name&service=$f_serv_desc'><b>Disable notifications for host</b></a></td></tr>\r\n";
 $body .= "<tr bgcolor=#eeeeee><td></td><td><a href='https://$url/cgi-bin/cmd.cgi?cmd_typ=29&host=$f_host_name&service=$f_serv_desc'><b>Disable notifications for all services on host</b></a></td></tr>\r\n";
 $body .= "</table></table></body></html> \r\n";

 $headers = "From: $from\r\n";
 $headers = $headers."Content-type: text/html\r\n";

 /* Send eMail Now... */
 mail($f_to, $subject, $body, $headers);



?>




